protected/controllers/AlbumController.php
<?php

class AlbumController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'suggestMusique'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'suggestMusique'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'expression' => 'Yii::app()->user->isAdmin()',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->renderPartial('view', array(
            'model' => $this->loadModel($id),
        ),false,true);
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Album;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        
        if (isset($_POST['Album']) && !Yii::app()->user->isGuest) {
            
            $codeErreur = true;
            $model->attributes = $_POST['Album'];
            $model->idutilisateur = Yii::app()->user->idutilisateur;
            if($codeErreur = $model->save()){
                $listMusique = explode(";", $_POST['musiqueStock']);
                for ($i = 0; $codeErreur && $i < count($listMusique) - 1; $i++) {
                    $musique = Musique::model()->findByAttributes(array('titre' => $listMusique[$i]));
                    $$i = new Appartient;
                    $$i->idalbum = $model->idalbum;
                    $$i->idmusique = $musique->idmusique;
                    $codeErreur = $codeErreur && ($$i->save());
                }                
            }
            if($codeErreur)
            {
                $this->renderPartial('view', array(
                    'model'=>Album::model()->with('musiques')->findByPk($model->idalbum)
                    ), false, true);
            } else {
                $this->renderPartial('create', array('model' => $model, 'message'=>"Erreur de création de l'album"), false, true);
            }
                //$this->renderPartial(array('../utilisateur/view', 'id' => Yii::app()->user->idutilisateur), false, true);//, 'codeErreur'=>true), false, true);
            
        } else {
            $this->renderPartial('create', array('model' => $model), false, true);
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Album'])) {
            $model->attributes = $_POST['Album'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idalbum));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Album');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Album('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Album']))
            $model->attributes = $_GET['Album'];

        $this->renderPartial('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Album the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Album::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Album $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'album-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionSuggestMusique() {
        if (!Yii::app()->user->isGuest) {
            $request = trim($_GET['term']);
            $id = Yii::app()->user->idutilisateur;
            $request = strtolower(addcslashes($request, '%_')); // escape LIKE's special characters

            $criteria = new CDbCriteria(array(
                'condition' => "lower(titre) LIKE :match AND idutilisateur=:id",
                'params' => array(':match' => "%$request%", ':id' => $id)
                    ));
            $model = Musique::model()->findAll($criteria);
            $data = array();
            foreach ($model as $musique) {
                $data[] = $musique->titre;
            }
            echo CJSON::encode($data);
            Yii::app()->end();
        }
    }

}

protected/controllers/MusiqueController.php
<?php

class MusiqueController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'delete', 'update', 'ajouterEnFavori', 'supprimerDeMesFavoris', 'getMusic', 'search', 'calculStat', 'modifierNote', 'modifierEcoute'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'statMusique'),
                'expression' => 'Yii::app()->user->isAdmin()',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /* Liste toutes les musiques de l'artiste */

    public function actionMesSons() {
        $idutil = Yii::app()->user->idutilisateur;

        $criteria1 = new CDbCriteria();
        $criteria1->alias = 'm';
        $criteria1->condition = 'm.numeroutilisateur=' . $idutil;
        $criteria1->order = 'titre ASC';

        //Récupération des recettes de l'utilisateur
        $dataProvider = new CActiveDataProvider('Musique', array('criteria' => $criteria1));

        $this->renderPartial('messons', array('dataProvider' => $dataProvider));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {

        $model = new Musique;
        $model2 = new Genre;
        $msg = '';

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if (isset($_POST['Musique'])) {

            $model->attributes = $_POST['Musique'];
            $model->dateajout = date("Y-m-d H:i:s"); //Obligé car MySQL 5.7 n'accepte pas les CURRENT_TIMESTAMP 
            $model->idutilisateur = Yii::app()->user->idutilisateur;

            // Pour l'upload de la musique
            $rnd = rand(0, 9999);  // generate random number between 0-9999
            $uploadedFile = CUploadedFile::getInstance($model, 'lienmusique');
            //var_dump($uploadedFile);
            $fileName = "{$rnd}-{$uploadedFile}";  // random number + file name                        
            if ($uploadedFile != null) {
                $model->lienmusique = $fileName;
                $model->urlmusique = $fileName;
            }

            if ($model->save()) {

                if ($uploadedFile != null) {
                    $uploadedFile->saveAs(Yii::app()->basePath . '/../musique/' . $model->idmusique . substr($model->urlmusique,strrpos($model->urlmusique, '.')));
                    $model->urlmusique = $model->idmusique . substr($model->urlmusique,strrpos($model->urlmusique, '.'));
                    $model->save();
                }

                if (!empty($_POST["Musique"]["genre"])) {
                    for ($i = 0; $i < count($_POST["Musique"]["genre"]); $i++) {
                        $$i = new Musiquegenre;
                        $$i->idmusique = $model->idmusique;
                        $$i->idgenre = $_POST["Musique"]["genre"][$i];
                        $$i->save();
                    }
                }
            }
            $msg = 'La musique à été ajoutée !';
        }

        $model = new Musique;
        $model2 = Genre::model()->findAll();

        if (Yii::app()->request->isAjaxRequest)
            $this->renderPartial('create', array(
                'model' => $model, 'model2' => $model2, 'msg' => $msg
            ));
        else
            $this->render('create', array(
                'model' => $model, 'model2' => $model2, 'msg' => $msg
            ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Musique'])) {
            $model->attributes = $_POST['Musique'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idmusique));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $musique = $this->loadModel($id);
        if ($musique != null) {
            Appartient::model()->deleteAll('idmusique=:id', array('id'=>$id));
            Musiquegenre::model()->deleteAll('idmusique=:id', array('id'=>$id));
            Nbecoute::model()->deleteAll('idmusique=:id', array('id'=>$id));
            Aenfavorismusique::model()->deleteAll('idmusique=:id', array('id'=>$id));
            
            //On supprime le fichier du serveur
            $musique->delete();
            if (file_exists($_SERVER['DOCUMENT_ROOT'].Yii::app()->baseUrl . '/musique/' . $musique->urlmusique))
                unlink($_SERVER['DOCUMENT_ROOT'].Yii::app()->baseUrl . '/musique/' . $musique->urlmusique);
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Musique');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionAjouterEnFavori() {
        $res = array();
        if (Yii::app()->request->isAjaxRequest) {
            if (isset($_POST['idutilisateur']) && isset($_POST['idmusique'])) {
                if (Aenfavorismusique::model()->findByAttributes(array('idmusique' => $_POST['idmusique'], 'idutilisateur' => $_POST['idutilisateur'])) == null) {
                    $fav = new Aenfavorismusique();
                    $fav->idmusique = $_POST['idmusique'];
                    $fav->idutilisateur = $_POST['idutilisateur'];
                    $res['codeErreur'] = $fav->save();
                    if ($res['codeErreur'])
                        $res['message'] = "Ajouté en favori !";
                    else
                        $res['message'] = "La musique n'a pas été ajoutée en favori !";
                }else {
                    $res['codeErreur'] = false;
                    $res['message'] = "Ajouté en favori !";
                }
            } else {
                $res['codeErreur'] = false;
                $res['message'] = "La musique n'a pas été ajouté en favori !" . print_r($_POST);
            }
        }

        echo json_encode($res, true);
    }

    public function actionSupprimerDeMesFavoris() {
        $res = array();
        if (Yii::app()->request->isAjaxRequest) {
            if (isset($_POST['idutilisateur']) && isset($_POST['idmusique'])) {
                $fav = Aenfavorismusique::model()->findByAttributes(array('idmusique' => $_POST['idmusique'], 'idutilisateur' => $_POST['idutilisateur']));
                if ($fav != null) {
                    $res['codeErreur'] = $fav->delete();
                    if ($res['codeErreur'])
                        $res['message'] = "La musique a été supprimée de mes favoris !";
                    else
                        $res['message'] = "La musique n'a pas été supprimée de mes favoris !";
                }else {
                    $res['codeErreur'] = true;
                    $res['message'] = "La musique a été supprimée de mes favoris !";
                }
            } else {
                $res['codeErreur'] = false;
                $res['message'] = "La musique n'a pas été supprimée de mes favoris !";
            }
        } else {
            $res['codeErreur'] = false;
            $res['message'] = "La musique n'a pas été supprimée de mes favoris !";
        }

        echo json_encode($res, true);
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Musique('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Musique']))
            $model->attributes = $_GET['Musique'];

        $this->renderPartial('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.

protected/views/album/_form.php
<?php
/* @var $this AlbumController */
/* @var $model Album */
/* @var $form CActiveForm */
?>
<?php
$baseUrl = Yii::app()->baseUrl;
//echo $baseUrl;
$cs = Yii::app()->getClientScript();
$cs->registerScriptFile($baseUrl . '/themes/hebo/js/choisirMusique.js', CClientScript::POS_END);

if(isset($message)){
    ?>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>Erreur !</strong> <?php echo $message; ?>
    </div>
<?php

}
?>

<div class="form">
<h1>Créer un album</h1>
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'album-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => false,
    ));
    ?>

<?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model, 'libellealbum'); ?>
        <?php echo $form->textField($model, 'libellealbum', array('size' => 60, 'maxlength' => 100)); ?>
<?php echo $form->error($model, 'libellealbum'); ?>
    </div>

    <?php
    $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
        'name' => 'Musique',
        'source' => $this->createUrl("album/suggestMusique"),
        'options' => array(
            'minLength' => '1',
        ),
        'htmlOptions' => array(
            'id' => 'Musique',
            'style' => 'width:30%;display:inline-block;',
        )
    ));
    ?>


    <?php echo CHtml::Button("Ajouter", array('onclick' => 'js:validerAjax($("#Musique").val());', 'class' => 'btn btn-primary', 'style' => 'display:inline-block;')); ?>

    <?php
    //remplissage champs caché
    $lesmusiques = "";
    foreach ($model->musiques as $musique) {
        $lesmusiques .= $musique->titre . ";";
    }
    ?>
    <input type="hidden" name="musiqueStock" id="musiqueStock" value='<?php echo $lesmusiques; ?>' >
    <?php echo $form->error($model, 'Musique'); ?>

    <input type="hidden" name="adresse" id="adresse" value="<?php echo Yii::app()->request->hostinfo. Yii::app()->request->baseUrl; ?>" >
    <?php echo $form->error($model, 'Musique'); ?>

    <div id="Musc">
        <table id="tableContient" class="table table-striped table-bordered table-hover"><tr><th>Musiques ajoutées</th></tr>
            <?php
            //remplissage tableau
            if (!$model->isNewRecord) {
                foreach ($model->musiques as $musique) {
                    echo "<tr>";
                    echo "<td style=\"padding-right:1%;\">tg" . $musique->titre . "</td>";
                    echo "<td><div id='deleteButton' style=\"display:inline-block;\" onclick='deleteRow(this)'>X</div></td></tr>";
                }
            }
            ?>  
        </table>
    </div>

    <div class="button-wrapper-wrapper">
        <div class="button-wrapper">
            <div class="button-swag button-upload">
        <?php
        //echo CHtml::submitButton($model->isNewRecord ? "Créer l'album" : "Mettre à jour l'album", array('class'=>'btn')); 
        if ($model->isNewRecord) {

            echo CHtml::ajaxSubmitButton(
                "Créer l'album",
                CHtml::normalizeUrl(array('album/create')),
                    array(
                        'data' => 'js:$(this).parents("form").serialize()',
                        'success' => 'function(data){
                                            $("#content").html(data);
                                          }',
                        'error' => 'function(data){console.log(data);}'
                    ), array(
                'id' => 'ajaxSubmitBtn',
                'name' => 'ajaxSubmitBtn',
                'class'=>'btn'
            ));
        }
        ?>
            <p>Créer l'album</p>
            </div>
        </div>
    </div>
    <p class="note">Les champs marqués d'une astérisque (<span class="required">*</span>) sont obligatoires.</p>

        <?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/album/_search.php
<?php
/* @var $this AlbumController */
/* @var $model Album */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'idalbum'); ?>
		<?php echo $form->textField($model,'idalbum'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'libellealbum'); ?>
		<?php echo $form->textField($model,'libellealbum',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/album/_view.php
<?php
/* @var $this AlbumController */
/* @var $data Album */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idalbum')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idalbum), array('view', 'id'=>$data->idalbum)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('libellealbum')); ?>:</b>
	<?php echo CHtml::encode($data->libellealbum); ?>
	<br />


</div>

protected/views/album/admin.php
<?php
/* @var $this AlbumController */
/* @var $model Album */

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#album-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Gérer les albums</h1>

<p>
Vous pouvez éventuellement utiliser les opérateurs de comparaisons(<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
ou <b>=</b>) au début de chacun de vos valeurs de recherches pour spécifier comment la comparaison doit se faire.
</p>

<?php //echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'album-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'idalbum',
		'libellealbum',
		array(
			'class'=>'CButtonColumn',
                    
		),
	),
)); ?>

protected/views/album/create.php
<?php
/* @var $this AlbumController */
/* @var $model Album */
?>


<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/album/index.php
<?php
/* @var $this AlbumController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Albums',
);

$this->menu=array(
	array('label'=>'Create Album', 'url'=>array('create')),
	array('label'=>'Manage Album', 'url'=>array('admin')),
);
?>

<h1>Albums</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/album/update.php
<?php
/* @var $this AlbumController */
/* @var $model Album */

$this->breadcrumbs=array(
	'Albums'=>array('index'),
	$model->idalbum=>array('view','id'=>$model->idalbum),
	'Update',
);

$this->menu=array(
	array('label'=>'List Album', 'url'=>array('index')),
	array('label'=>'Create Album', 'url'=>array('create')),
	array('label'=>'View Album', 'url'=>array('view', 'id'=>$model->idalbum)),
	array('label'=>'Manage Album', 'url'=>array('admin')),
);
?>

<h1>Update Album <?php echo $model->idalbum; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/album/view.php
<?php
/* @var $this AlbumController */
/* @var $model Album */

?>
<div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    L'album a été ajouté !
</div>
<h1>Album <?php echo $model->libellealbum; ?></h1>

<table id="tablemusiques" class="tablesorter table table-striped table-bordered table-hover">
                <thead>
                        <th class="thtitre">Titre</th>
                        <th class="thdate">Date</th>
                        <th class="thalbum">Album</th>
                        <th class="thsuppr"></th>
                </thead>
            <?php
                $i=0;
                    foreach($model->musiques as $musique)
                    {
                        echo "<tr id='$musique->idmusique'>";
                        echo "<td>";
                        echo '<div class="jp-controls musique" titre="'.$musique->titre.'" url="/musique/'.$musique->urlmusique.'">
                                    <button class="jp-play" onclick="loadMusique(this);loadStat();" role="button" tabindex="0">play</button>
                                    <button class="jp-stop" onclick="stop();stopStat();" role="button" tabindex="0">stop</button>
                                </div>';
                        echo "$musique->titre<div id='audiospectrum$i' class='audiospec'></div></td>";
                        echo "<td>$musique->dateajout</td>";
                        echo "<td>$model->libellealbum</td>";
                        echo "<td>";
                        echo CHtml::ajaxSubmitButton(
                                    'Delete', Yii::app()->createUrl('musique/delete',array("id"=>$musique->idmusique)),array(
                                    'type' => 'POST',
                                    'success' => 'function(){ $("tr[id='.$musique->idmusique.']").remove();}'
                )
        ); 
                        echo "</td>";
                        echo '</tr>';
                        
                        $i++;
                    }
            ?>
            </table>

    <script type="text/javascript" src="<?php echo $baseUrl;?>/js/tablesorter/jquery.tablesorter.min.js"></script> 