protected/models/Post.php
<?php

/**
 * This is the model class for table "post".
 *
 * The followings are the available columns in table 'post':
 * @property string $idpost
 * @property integer $idutilisateur
 * @property string $contenu
 * @property string $date
 */
class Post extends CActiveRecord
{
    const LIMIT = 5;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'post';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('idutilisateur, contenu', 'required'),
			array('idutilisateur', 'numerical', 'integerOnly'=>true),
			array('date', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('idpost, idutilisateur, contenu, date', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
                    'utilisateur'=>array(self::BELONGS_TO, 'Utilisateur', 'idutilisateur'),
                    'commentaires'=>array(self::HAS_MANY, 'Commentaire', 'idpost', 'order'=>'commentaires.date DESC')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idpost' => 'Idpost',
			'idutilisateur' => 'Idutilisateur',
			'contenu' => 'Contenu',
			'date' => 'Date',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idpost',$this->idpost,true);
		$criteria->compare('idutilisateur',$this->idutilisateur);
		$criteria->compare('contenu',$this->contenu,true);
		$criteria->compare('date',$this->date,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/CommentaireController.php
<?php

class CommentaireController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'delete'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Commentaire;
        $result = array('codeErreur' => 'false');
        if (isset($_POST['contenu'])) {
            if (!empty(trim($_POST['contenu']))) {
                $model->attributes = $_POST;
                $model->date = $_POST['date'];
                $result['codeErreur'] = $model->save();
                $result[] = $_POST;
                echo CJSON::encode($result);
            }
        } else {
            $this->renderPartial('create', array(
                'model' => $model,
                    ), false, true);
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Commentaire'])) {
            $model->attributes = $_POST['Commentaire'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idcommentaire));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Commentaire');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Commentaire('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Commentaire']))
            $model->attributes = $_GET['Commentaire'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Commentaire the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Commentaire::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Commentaire $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'commentaire-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/controllers/PostController.php
<?php

class PostController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            //'delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'delete'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Post;
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (isset($_POST['contenu'])) {
            $result = array('codeErreur' => 'false');
            if (!empty(trim($_POST['contenu']))) {
                $model->attributes = $_POST;
                $model->date = $_POST['date'];
                if ($model->save())
                    $result['codeErreur'] = true;

                $result["data"] = $_POST;
                $result["data"]["idpost"] = $model->idpost;
            }
            echo CJSON::encode($result);
        } else {


            $this->renderPartial('create', array(
                'model' => $model,
                    ), false, true);
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Post'])) {
            $model->attributes = $_POST['Post'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idpost));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $post = $this->loadModel($id);
        $post->delete();
        Commentaire::model()->deleteAll('idpost=:id',array('id'=>$id) );
        
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Post');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Post('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Post']))
            $model->attributes = $_GET['Post'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Post the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Post::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Post $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'post-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/post/_form.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'post-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'idutilisateur'); ?>
		<?php echo $form->textField($model,'idutilisateur'); ?>
		<?php echo $form->error($model,'idutilisateur'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'contenu'); ?>
		<?php echo $form->textArea($model,'contenu',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'contenu'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date'); ?>
		<?php echo $form->textField($model,'date'); ?>
		<?php echo $form->error($model,'date'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/post/_search.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'idpost'); ?>
		<?php echo $form->textField($model,'idpost',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'idutilisateur'); ?>
		<?php echo $form->textField($model,'idutilisateur'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'contenu'); ?>
		<?php echo $form->textArea($model,'contenu',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date'); ?>
		<?php echo $form->textField($model,'date'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/post/_view.php
<?php
/* @var $this PostController */
/* @var $data Post */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idpost')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idpost), array('view', 'id'=>$data->idpost)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idutilisateur')); ?>:</b>
	<?php echo CHtml::encode($data->idutilisateur); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('contenu')); ?>:</b>
	<?php echo CHtml::encode($data->contenu); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
	<?php echo CHtml::encode($data->date); ?>
	<br />


</div>

protected/views/post/admin.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Create Post', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#post-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Posts</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'post-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'idpost',
		'idutilisateur',
		'contenu',
		'date',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/post/create.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Manage Post', 'url'=>array('admin')),
);
?>

<h1>Create Post</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/index.php
<?php
/* @var $this PostController */
/* @var $dataProvider CActiveDataProvider */
if (!empty($posts)) {

    foreach ($posts as $post) {
        echo '<tr idpost="' . $post->idpost . '">';
        echo '<td style="vertical-align:middle;">';
        echo "<div>";
        echo '<img style="width:40px;height:50px;" src="' . Yii::app()->baseUrl . '/img/photosprofiles/' . $post->utilisateur->urlphoto . '"/>';
        echo "\t" . $post->utilisateur->pseudo;
        if (Yii::app()->user->idutilisateur == $post->idutilisateur) {
            ?>
                <input class="btn btn-danger btn-small" style="float:right;" id="btnSupprimerPost<?php echo $post->idpost; ?>" type="button" onclick='supprimerPost("<?php echo Yii::app()->createUrl('post/delete', array('id'=>$post->idpost));?>",<?php echo $post->idpost; ?>)' value="Supprimer"/>
            <?php
            /*echo CHtml::ajaxSubmitButton(
                'Supprimer', Yii::app()->createUrl('post/delete', array("id" => $post->idpost)), array(
                'type' => 'POST',
                'success' => 'function(){ $("tr[idpost=' . $post->idpost . ']").remove();}',
                'error' => 'function(result){console.log(result);}'
                    ), array('style' => 'float:right;', 'class' => 'btn btn-danger btn-small'));*/
        }
        echo "</div>";


        echo "<p>" . $post->contenu . "</p>";
        echo "<div style=\"float:right;font-size:10px;\">Publié le " . $post->date . "</div>";
        echo '<div style="clear:both;"></div>';
        ?><textarea id="commentaire<?php echo $post->idpost; ?>" placeholder="Posez votre commentaire ici !" style="width:90%;"></textarea>
        <input type="hidden" id="valeurcommentaire<?php echo $post->idpost;?>" value=""/>
        <script>
            $("#commentaire<?php echo $post->idpost; ?>").bind("input propertychange", function(){
               $("#valeurcommentaire<?php echo $post->idpost;?>").val($("#commentaire<?php echo $post->idpost; ?>").val()); 
            });
        </script>
        
        <input style="float:right;" type="submit" onclick="commenter(this, <?php echo $post->idpost; ?>)" id="btnCommentaire<?php echo $post->idpost; ?>" value="Commenter" class="btn btn-primary btn-small"/>
        <div style="clear:both;"></div>
        <?php
         
        //Affichage des commentaires
        if (!empty($post->commentaires)) {
            echo "<a id=\"btnVoirCommentaires" . $post->idpost . "\" onClick=\"voirTousLesCommentaires(" . $post->idpost . ");\">Voir les commentaires</a>";
            echo "<a id=\"btnCacherCommentaires" . $post->idpost . "\" class=\"btnCacherCommentaires\" onClick=\"cacherTousLesCommentaires(" . $post->idpost . ");\">Cacher les commentaires</a>";
            echo "<table style=\"width:100%;\"class=\"commentaires\" id=\"commentairesDuPost" . $post->idpost . "\">";
            echo "<tbody>";

            foreach ($post->commentaires as $commentaire) {

                echo '<tr idcommentaire="' . $commentaire->idcommentaire . '">';

                echo "<td style=\"vertical-align:middle;\">";
                echo "<div>";
                echo "<img style=\"width:40px;height:50px;\" src=\"" . Yii::app()->baseUrl . '/img/photosprofiles/' . $commentaire->utilisateur->urlphoto . "\">";
                echo "\t" . $commentaire->utilisateur->pseudo;
                //On peut supprimer son commentaire mais aussi le commentaire d'un autre s'il est relatif au post courant
                if (Yii::app()->user->idutilisateur == $commentaire->idutilisateur || Yii::app()->user->idutilisateur == $post->idutilisateur) {

                    echo CHtml::ajaxSubmitButton(
                        'Supprimer', Yii::app()->createUrl('commentaire/delete', array("id" => $commentaire->idcommentaire)), array(
                        'type' => 'POST',
                        'success' => 'function(){ $("tr[idcommentaire=' . $commentaire->idcommentaire . ']").remove();}',
                        'error' => 'function(result){console.log(result);}'
                            ), array('style' => 'float:right;', 'class' => 'btn btn-danger btn-small'));
                }

                echo "</div>";
                echo "<p>" . $commentaire->contenu . "</p>";
                echo "<div style=\"float:right;font-size:10px;\">Publié le " . $commentaire->date . "</div>";
                echo "</td></tr>";
            }

         
         
            echo "</tbody>";
            echo "</table>";
        }

        echo "</td>";
        echo "</tr>";
    }
}
?>

protected/views/post/update.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	$model->idpost=>array('view','id'=>$model->idpost),
	'Update',
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Create Post', 'url'=>array('create')),
	array('label'=>'View Post', 'url'=>array('view', 'id'=>$model->idpost)),
	array('label'=>'Manage Post', 'url'=>array('admin')),
);
?>

<h1>Update Post <?php echo $model->idpost; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/view.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	$model->idpost,
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Create Post', 'url'=>array('create')),
	array('label'=>'Update Post', 'url'=>array('update', 'id'=>$model->idpost)),
	array('label'=>'Delete Post', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->idpost),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Post', 'url'=>array('admin')),
);
?>

<h1>View Post #<?php echo $model->idpost; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'idpost',
		'idutilisateur',
		'contenu',
		'date',
	),
)); ?>