protected/controllers/CommentaireController.php
<?php

class CommentaireController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'delete'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Commentaire;
        $result = array('codeErreur' => 'false');
        if (isset($_POST['contenu'])) {
            if (!empty(trim($_POST['contenu']))) {
                $model->attributes = $_POST;
                $model->date = $_POST['date'];
                $result['codeErreur'] = $model->save();
                $result[] = $_POST;
                echo CJSON::encode($result);
            }
        } else {
            $this->renderPartial('create', array(
                'model' => $model,
                    ), false, true);
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Commentaire'])) {
            $model->attributes = $_POST['Commentaire'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idcommentaire));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Commentaire');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Commentaire('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Commentaire']))
            $model->attributes = $_GET['Commentaire'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Commentaire the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Commentaire::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Commentaire $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'commentaire-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/controllers/PostController.php
<?php

class PostController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            //'delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'delete'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Post;
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (isset($_POST['contenu'])) {
            $result = array('codeErreur' => 'false');
            if (!empty(trim($_POST['contenu']))) {
                $model->attributes = $_POST;
                $model->date = $_POST['date'];
                if ($model->save())
                    $result['codeErreur'] = true;

                $result["data"] = $_POST;
                $result["data"]["idpost"] = $model->idpost;
            }
            echo CJSON::encode($result);
        } else {


            $this->renderPartial('create', array(
                'model' => $model,
                    ), false, true);
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Post'])) {
            $model->attributes = $_POST['Post'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->idpost));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $post = $this->loadModel($id);
        $post->delete();
        Commentaire::model()->deleteAll('idpost=:id',array('id'=>$id) );
        
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Post');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Post('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Post']))
            $model->attributes = $_GET['Post'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Post the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Post::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Post $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'post-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/site/zones/zone1/actualites.php
<div class="tab-pane active" id="actualites">

    <h3>Ecrivez votre message : </h3>
    <textarea id="contenu" style="width:90%; resize: vertical;" name="post"></textarea>
    <?php
    echo CHtml::ajaxSubmitButton('Publier', Yii::app()->createUrl('post/create'), array(
        'type' => 'POST',
        'data' => 'js:{"idutilisateur": ' . Yii::app()->user->idutilisateur . ', "contenu": $("#contenu").val(), "date":getcurrenttime()}',
        'success' => 'js:function(result){'
        . 'result = JSON.parse(result); '
        . 'if(result.codeErreur == true){'
        . 'creerTrPost(result.data, "debut");'
        . '}else{'
        . 'alert("message non publié"); }'
        . '}',
        'error' => 'js:function(result){console.log(result);}'
            ), array('class' => 'btn btn-small btn-primary', 'style' => 'float:right;', 'name' => 'publierMessage'));
    ?>    <table id="tableposts" class="table table-striped table-hover">
        <tbody>

            <?php $this->renderPartial('../post/index', array('posts' => $posts)); ?>
    </table>
</tbody>
<?php
if (!empty($posts)) {
    echo CHtml::hiddenField('posts_lim_inf', Post::LIMIT, array('id' => 'posts_lim_inf'));
    echo CHtml::button('Voir les posts plus anciens ...', array('id' => 'btnVoirPostsPlusAnciens', 'class' => 'btn btn-small'))
    /* echo CHtml::ajaxSubmitButton(
      'Voir les posts plus anciens...', Yii::app()->createUrl("utilisateur/getnposts", array("posts_lim_inf"=>)), array(
      'type' => 'GET',
      'success' => 'js:function(result){
      console.log("ancienne val : "+$("#posts_lim_inf").val());
      $("#posts_lim_inf").val(result.posts_lim_inf);
      console.log("nouvelle val : "+$("#posts_lim_inf").val());

      $("#tableposts tbody").append(result);

      }',
      'error'=>'function(data){console.log(data);}'
      )); */
    ?>
    <script>
        $("#btnVoirPostsPlusAnciens").click(function () {
            $.get("<?php echo Yii::app()->createUrl('utilisateur/getnposts'); ?>",
                    'posts_lim_inf=' + $("#posts_lim_inf").val(),
                    function (result, status, xhr) {
                        if (status == "success") {
                            result = JSON.parse(result);
                            if (result.codeErreur) {
                                $("#posts_lim_inf").val(result.posts_lim_inf);
                                $("#tableposts tbody").append(result.data);
                            } else
                                alert("false");
                        } else {
                            console.log(xhr);
                        }
                    }
            );
        });
    </script>
    <?php
}
?>
</div>

<script id="script">
            function getcurrenttime() {
                var currentdate = new Date();
                return currentdate.getFullYear() + "-"
                        + (currentdate.getMonth() + 1) + "-"
                        + currentdate.getDate() + " "
                        + currentdate.getHours() + ":"
                        + currentdate.getMinutes() + ":"
                        + currentdate.getSeconds();
            }

            function voirTousLesCommentaires(idpost) {
                $("#commentairesDuPost" + idpost).slideDown();
                $("#btnVoirCommentaires" + idpost).hide();
                $("#btnCacherCommentaires" + idpost).show();

            }

            function cacherTousLesCommentaires(idpost) {
                $("#commentairesDuPost" + idpost).slideUp();
                $("#btnVoirCommentaires" + idpost).show();
                $("#btnCacherCommentaires" + idpost).hide();

            }

            

            function creerTrPost(data, pos) {
                var url = "\"<?php echo Yii::app()->createUrl('post/delete'); ?>" + "/" + data.idpost + "\"";

                
                var tr = $("<tr/>");
                tr.attr('idpost',data.idpost);
                var td = $("<td/>");
                var div = $("<div/>");
                var image = $("<img/>");
                image.css({width:'40px', height:'50px'});
                image.attr('src', "<?php echo Yii::app()->baseUrl . '/img/photosprofiles/' . Yii::app()->user->getUrlPhoto(); ?>");
                var boutonSupprimerPost = $("<input/>");
                boutonSupprimerPost.attr('type', 'button');
                boutonSupprimerPost.attr('class', 'btn btn-danger btn-small');
                boutonSupprimerPost.val('Supprimer');
                boutonSupprimerPost.attr('id','deletePost' + data.idpost);
                boutonSupprimerPost.css('float', 'right');
                boutonSupprimerPost.click(function(){supprimerPost(url,data.idpost)});
                
                div.append(image);
                div.append("\t<?php echo Yii::app()->user->getPseudo(); ?>");
                div.append(boutonSupprimerPost);
                td.append(div);
                td.append('<p>'+data.contenu+'</p>');
                td.append('<div style="float:right;font-size:10px;">Publié le ' + data.date + '</div>');
                tr.append(td);
                
                if (pos == "debut")
                    $("#tableposts tbody").prepend(tr);
                else
                    $("#tableposts tbody").append(tr);

            }

            function supprimerPost(url, idpost) {
                //alert("2");
                $.post(url, function (data, status, xhr) {
                    if (status == "success")
                        $('tr[idpost="' + idpost + '"]').remove();
                    else
                        console.log(data);
                });
            }

            $(".commentaires, .btnCacherCommentaires").each(function () {
                $(this).hide();
            });

            function commenter(obj, idpost) {

                var selecteur = "#valeurcommentaire" + idpost;
                $.post(
                        "<?php echo Yii::app()->createUrl("commentaire/create"); ?>",
                        {"idutilisateur": <?php echo Yii::app()->user->idutilisateur; ?>, "idpost": idpost, "contenu": $(selecteur).val(), "date": getcurrenttime()},
                        function (data, status) {
                            if (status == "success") {
                                console.log(data);
                                data = $.parseJSON(data);
                                if (data.codeErreur) {
                                    //On recharge la page
                                    $.get("<?php echo Yii::app()->createUrl("site/index") ?>", function (result, status) {
                                        $("#content").html(result);
                                        //alert("ajouté");
                                    });
                                } else {
                                    alert('pas ok');
                                }




                            } else if (status == "error") {
                                alert("Le commentaire n'a pas été publié !");
                            }

                        }
                );
                //});
            }
            
    $("a").click(function()
    {
        $('div').each(function(){
            if($(this).prop('offsetHeight') < $(this).prop('scrollHeight') && $(this).css("overflow")!="hidden")
            {
                $(this).mCustomScrollbar({scrollInertia: 10});
            }
            
        });
    });
</script>

protected/views/site/zones/zone1/amis.php
<div class="tab-pane" id="amis">
    <?php
    
    //Affichage des invitations
    //print_r(Yii::app()->user->getInvitationsAmis());
    if (count(Yii::app()->user->getInvitationsAmis())>0) {
        echo '<h3 id="invittitre">Nouvelles invitations</h3>';
        foreach (Yii::app()->user->getInvitationsAmis() as $invitation) {
            echo '<div>';

            echo CHtml::image(Yii::app()->baseUrl . '/img/photosprofiles/' . $invitation->urlphoto, Yii::app()->baseUrl . '/img/photosprofiles/team-member.png', array('width' => '80px', 'height' => '80px'));
            echo $invitation->prenom . ' ' . $invitation->nom;
            echo '<div class="invitation" style="float:right;height:40px; padding-top:20px;">';
            echo CHtml::ajaxSubmitButton('Accepter l\'invitation', array('utilisateur/accepterami'), array('data' => array('idami' => $invitation->idutilisateur),
                'success' => 'function(data){   
                                                var res = JSON.parse(data);
                                                alert(res.message);
                                                if(res.status){
                                                    var div = $("#btn_accepterami' . $invitation->idutilisateur . '").parent().parent();
                                                    $("#btn_accepterami' . $invitation->idutilisateur . '").parent().parent().remove();
                                                    div.children().last().remove();
                                                    $("#amish3").after(div.html());
                                                    if($(".invitation").length==0)
                                                    {
                                                        $("#invittitre").text("Aucune invitation");
                                                    }
                                                }
                                            }'
                    ), array('id' => 'btn_accepterami' . $invitation->idutilisateur, 'class' => 'btn-success'));
            echo ' ';
            echo CHtml::ajaxSubmitButton('Refuser l\'invitation', array('utilisateur/refuserami'), array('data' => array('idami' => $invitation->idutilisateur),
                'success' => 'function(data){                                   
                                                var res = JSON.parse(data);
                                                alert(res.message);
                                                if(res.status){
                                                    $("#btn_accepterami' . $invitation->idutilisateur . '").parent().parent().remove();
                                                    if($(".invitation").length==0)
                                                    {
                                                        $("#invittitre").text("Aucune invitation");
                                                        $("a#amis").text("Amis");
                                                    }
                                                }

                                            }'
                    ), array('id' => 'btn_refuserami' . $invitation->idutilisateur, 'class' => 'btn-danger'));
            echo '</div>';
            echo '</div>';
        }
    } else
        echo '<h3>Aucune invitation</h3>';

    //Affichage des amis
    $nbAmis = count(Yii::app()->user->getAmis());
    if ($nbAmis > 0) {
        echo '<h3 id="amish3">Mes amis</h3>';
        foreach (Yii::app()->user->getAmis() as $ami) {
            echo '<div>';
            echo CHtml::image(Yii::app()->baseUrl . '/img/photosprofiles/' . $ami->urlphoto, Yii::app()->baseUrl . '/img/photosprofiles/team-member.png', array('width' => '80px', 'height' => '80px'));
            echo $ami->prenom . ' ' . $ami->nom;
            
            //Bouton supprimer en amis
            //Si l'invitation est envoyée (que l'autre ait répondu ou non)
            echo CHtml::ajaxSubmitButton('Retirer de ma liste d\'amis', array('utilisateur/supprimerami'), array('data' => array('idami' => $ami->idutilisateur),
                'success' => 'function(data){                                             
                                                var res = JSON.parse(data);
                                                alert(res.message);
                                                if(res.status)
                                                {
                                                    $("#btn_supprimerami'.$ami->idutilisateur.'").parent().remove();
                                                }

                                            }'
                    ), array('id' => 'btn_supprimerami'.$ami->idutilisateur, 'class' => 'btn btn-danger', 'style'=>'float:right;margin-top:30px;'));

            echo '</div>';
        }
    } else {
        echo '<h3>La liste d\'amis est vide !</h3>';
    }
    ?>

</div>

protected/views/site/zones/zone1/main.php
<div class="<?php if (Yii::app()->user->isGuest) echo 'span9';else echo 'span4'; ?>">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#actualites" data-toggle="tab">Actualités</a></li>
        <li><a href="#messons" data-toggle="tab">Mes sons</a></li>
        <li><a href="#mesfavoris" data-toggle="tab">Mes favoris</a></li>
        <li><a href="#amis" data-toggle="tab">Amis <?php $nbInvitations = count(Yii::app()->user->getInvitationsamis());
        if($nbInvitations>0)
            echo '('.$nbInvitations.')';
        ?></a></li>
    </ul>

    <div class="tab-content">
        <?php $this->renderPartial('zones/zone1/actualites', array('posts'=>$posts)); ?>
        <?php $this->renderPartial('zones/zone1/messons', array('messons'=>$messons)); ?>
        <?php $this->renderPartial('zones/zone1/mesfavoris', array('musiquesfavoris'=>$musiquesfavoris)); ?>
        <?php $this->renderPartial('zones/zone1/amis'); ?>
    </div>
</div>

protected/views/site/zones/zone1/mesfavoris.php
<div class="tab-pane" id="mesfavoris">

    <?php
    if (count($musiquesfavoris) == 0) {
        ?><h3>Vous n'avez pas de musiques dans vos favoris !</h3>
        <table class="table table-striped table-bordered table-hover">
            <tbody></tbody>
        </table>
    <?php
    } else {
        echo "<h3>Vos musiques favorites :</h3>";
        ?><table class="table table-striped table-bordered table-hover">
            <tbody>
    <?php foreach ($musiquesfavoris as $musique) { ?>
                    <tr idmusique="<?php echo $musique->idmusique; ?>"><td>
                            <div>
                                <div class="jp-controls musique" titre="<?php echo $musique->titre; ?>" url="<?php echo Yii::app()->request->hostinfo . '/' . Yii::app()->request->baseUrl . '/musique/' . $musique->urlmusique; ?>">
                                    <button class="jp-play" onclick="loadMusique(this)" role="button" tabindex="0">play</button>
                                    <button class="jp-stop" onclick="stop()"role="button" tabindex="0">stop</button>
                                </div>
                                <?php
                                echo $musique->titre . ' de ';
                                if ($musique->artiste != null) {
                                    echo CHtml::ajaxLink(
                                            $musique->artiste->pseudo, array('utilisateur/' . $musique->artiste->idutilisateur), array(
                                        'type' => 'POST',
                                        'success' => 'function(html){ $("#content").empty(); $("#content").append(html); }',
                                        'error' => 'function(html){console.log(html);}'
                                            )
                                    );
                                }
                                ?>
                            </div>
                        </td></tr>
                <?php }
                ?>
            </tbody>
        </table>
        <?php
    }
    ?>
</div>

protected/views/site/zones/zone1/messons.php
<div class="tab-pane" id="messons">
    
    <?php $this->renderPartial('../musique/index', array('messons'=>$messons)); ?>
    
</div>

protected/views/site/zones/zone1/recents.php
<?php
if(count($musiquesrecentes>0)){?>
    
<input type="hidden" id="urlcomplete" value="<?php echo Yii::app()->request->hostinfo.Yii::app()->request->baseUrl; ?>"/>
<input type="hidden" id="urletoilejaune" value="<?php echo Yii::app()->theme->baseUrl . '/img/etoile-jaune.png'; ?>"/>
<input type="hidden" id="urletoileblanche" value="<?php echo Yii::app()->theme->baseUrl . '/img/etoile-blanche.png'; ?>"/>
<?php if (!Yii::app()->user->isGuest){ ?><input type="hidden" id="idutilisateur" value="<?php echo Yii::app()->user->idutilisateur; ?>"/><?php } ?>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Titre</th>
            <th>Artiste</th>
            <th>Album(s)</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($musiquesrecentes as $musique) {
            echo "<tr>\n";
            echo '<td>';
            ?><div class="jp-controls musique" titre="<?php echo $musique->titre; ?>" url="<?php echo Yii::app()->request->hostinfo . '/' . Yii::app()->request->baseUrl . '/musique/' . $musique->urlmusique; ?>">
            <button class="jp-play" onclick="loadMusique(this)" role="button" tabindex="0">play</button>
            <button class="jp-stop" onclick="stop()"role="button" tabindex="0">stop</button>
        </div>
        <?php
        if (!Yii::app()->user->isGuest) {

            if ($musique->estDansMesFavoris(Yii::app()->user->idutilisateur))
                echo '<img class="etoile" onClick="gererFavori(this)" src="' . Yii::app()->theme->baseUrl . '/img/etoile-jaune.png" favori="true" idmusique="'.$musique->idmusique.'" />';
            else
                echo '<img class="etoile" onClick="gererFavori(this)" src="' . Yii::app()->theme->baseUrl . '/img/etoile-blanche.png" favori="false" idmusique="'.$musique->idmusique.'"/>';
        }

        echo $musique->titre . '</td>' . "\n";
        echo '<td>';
        if ($musique->artiste != null)
        {
            echo CHtml::ajaxLink(
                $musique->artiste->pseudo, 
                array('utilisateur/'.$musique->artiste->idutilisateur), 
                array (
                    'type'=>'POST',
                    'success'=>'function(html){ $("#content").empty(); $("#content").append(html); }',
                    'error'=>'function(html){console.log(html);}'
                    )
                );
        }else
            echo 'Artiste non renseigné !';
        echo '</td>' . "\n";
        echo '<td>';
        $nbalbums = count($musique->albums);
        if($nbalbums==0){
            echo 'Aucun album !';
        }else{
            $i=0;
            while($i<$nbalbums-1){
                echo $musique->albums[$i]->libellealbum.', ';
                $i++;
            }
            echo $musique->albums[$i]->libellealbum;
        }
        echo '</td>';
        echo "</tr>\n";
    }
    ?>
</tbody>
</table>
<?php }else
    echo '<h3>Aucune musique à afficher</h3>';

protected/views/site/zones/zone1/zone2.php
<div class="<?php if (Yii::app()->user->isGuest) echo 'span9';else echo 'span6'; ?>" id="zone2">
    <div class="row-fluid">
        <div>
            <ul class="nav nav-tabs">
                <li class="active"><a href="#recommandation" data-toggle="tab">Recommandation</a></li>
                <li><a href="#recents" data-toggle="tab">Récents</a></li>
                <?php
                if(!Yii::app()->user->isGuest){
                ?><li><a href="#playlists" data-toggle="tab">Playlists</a></li><?php
                } ?>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="recommandation"><?php $this->renderPartial('zones/zone2/recommandation'); ?></div>
                <div class="tab-pane" id="recents"><?php $this->renderPartial('zones/zone2/recents', array('musiquesrecentes'=>$musiquesrecentes)); ?></div>
                <div class="tab-pane" id="playlists"><h3>Settings</h3>These are settings, consectetur adipiscing elit. Quisque malesuada aliquam vulputate. Cras pulvinar erat ac velit eleifend porttitor at eu diam. Praesent elit mi, mattis vitae accumsan bibendum, porttitor non neque.</div>
            </div>
        </div>

    </div><!--/row-fluid-->

</div>